In [1]:
import numpy as np

In [2]:
matrix_1 = np.array([[3,4],[4,8]])
print(matrix_1)

[[3 4]
 [4 8]]


In [3]:
matrix_1.shape

(2, 2)

In [8]:
matrix_2 = np.array([[10,45,67],[55,86,89]])
print(matrix_2)

[[10 45 67]
 [55 86 89]]


In [9]:
matrix_2.shape

(2, 3)

In [11]:
random_integer_matrix = np.random.randint(100, size = (4,5))
print(random_integer_matrix)

[[11 60 78 92 34]
 [28  1 97 29 47]
 [81 10 87 72 86]
 [34 90 23 68 83]]


In [7]:
random_matrix = np.random.rand(5,5)
print(random_matrix)

[[0.55574952 0.33435393 0.10109402 0.80509715 0.14601872]
 [0.37173695 0.05264746 0.23184767 0.62086714 0.18257497]
 [0.9786603  0.76646016 0.08418389 0.23360742 0.07776985]
 [0.94112545 0.91063158 0.29601148 0.91677629 0.44661326]
 [0.31259655 0.81846402 0.2341654  0.67025487 0.36600251]]


In [13]:
ones_matrix = np.ones((4,5))
print(ones_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
ones_integer_matrix = np.ones((6,5) , dtype = int)
print(ones_integer_matrix)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [18]:
zeroes_matrix  = np.zeros ((5,6))
print(zeroes_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
ideantity_matrix =  np.eye(4,4)
print(ideantity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
a  = np.random.randint(100, size=(4,5))
print(a)

[[47 84 60 44 87]
 [48 80 37 45 25]
 [15  1 91 75 98]
 [68 69 58 73 47]]


In [22]:
transpose  = np.transpose(a)
print(transpose)

[[47 48 15 68]
 [84 80  1 69]
 [60 37 91 58]
 [44 45 75 73]
 [87 25 98 47]]
